<a href="https://colab.research.google.com/github/wlsgud623/vaccine_tweet_analysis/blob/main/VaccineTweet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
!pip install transformers==3

import transformers
from transformers import BertModel, BertTokenizer, AdamW, get_linear_schedule_with_warmup
import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from collections import defaultdict
from textwrap import wrap
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
import logging

logging.basicConfig(level=logging.ERROR)

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

print(device)

cuda:0


# Load Data

Kaggle API

In [2]:
!pip install kaggle
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"jinhyeoungbae","key":"dc42a77071a666d47d2e97f076322dfb"}'}

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
! kaggle datasets download -d kaushiksuresh147/covidvaccine-tweets
! kaggle datasets download -d gpreda/all-covid19-vaccines-tweets
! kaggle datasets download -d cosmos98/twitter-and-reddit-sentimental-analysis-dataset

 79% 42.0M/53.1M [00:00<00:00, 139MB/s]
100% 53.1M/53.1M [00:00<00:00, 134MB/s]
 87% 26.0M/29.9M [00:00<00:00, 129MB/s]
100% 29.9M/29.9M [00:00<00:00, 118MB/s]
  0% 0.00/10.0M [00:00<?, ?B/s]
100% 10.0M/10.0M [00:00<00:00, 92.4MB/s]


In [5]:
!unzip all-covid19-vaccines-tweets.zip
!unzip covidvaccine-tweets.zip
!unzip twitter-and-reddit-sentimental-analysis-dataset.zip

Archive:  all-covid19-vaccines-tweets.zip
  inflating: vaccination_all_tweets.csv  
Archive:  covidvaccine-tweets.zip
  inflating: covidvaccine.csv        
Archive:  twitter-and-reddit-sentimental-analysis-dataset.zip
  inflating: Reddit_Data.csv         
  inflating: Twitter_Data.csv        


Kaggle Tweet Data

In [6]:
first_vaccine_data = pd.read_csv("/content/covidvaccine.csv", nrows = 5000)
second_vaccine_data = pd.read_csv("/content/vaccination_all_tweets.csv", nrows = 5000)

In [7]:
first_vaccine_data.head()

user_name  ... is_retweet
0                 MyNewsNE  ...      False
1            Shubham Gupta  ...      False
2  Journal of Infectiology  ...      False
3                     Zane  ...      False
4       Ann-Maree O’Connor  ...      False

[5 rows x 13 columns]

In [8]:
second_vaccine_data.head()

id             user_name  ... favorites is_retweet
0  1340539111971516416            Rachel Roh  ...         0      False
1  1338158543359250433           Albert Fong  ...         1      False
2  1337858199140118533              eli🇱🇹🇪🇺👌  ...         0      False
3  1337855739918835717         Charles Adler  ...      2129      False
4  1337854064604966912  Citizen News Channel  ...         0      False

[5 rows x 16 columns]

In [9]:
data_column = ['user_name', 'user_description','user_location','user_followers','text']
first_vaccine_data = first_vaccine_data[data_column]
second_vaccine_data = second_vaccine_data[data_column]

In [10]:
print(first_vaccine_data['text'])

0       Australia to Manufacture Covid-19 Vaccine and ...
1       #CoronavirusVaccine #CoronaVaccine #CovidVacci...
2       Deaths due to COVID-19 in Affected Countries\n...
3       @Team_Subhashree @subhashreesotwe @iamrajchoco...
4       @michellegrattan @ConversationEDU This is what...
                              ...                        
4995    What you don’t know about schools #COVIDー19 #C...
4996    This pledge by 9 global pharma companies NOT t...
4997    @CaslerNoel @FLOTUS Sure let them hurry up wit...
4998    @TuckerCarlson Please watch this video from th...
4999    .@PressSec Have you been collecting those ader...
Name: text, Length: 5000, dtype: object


In [11]:
import re

def con(x):
  return ' '.join(re.sub("(#[A-Za-z0-9]+)|(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",x).split())
    
first_vaccine_data['text']=first_vaccine_data['text'].apply(con)
second_vaccine_data['text']=second_vaccine_data['text'].apply(con)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [12]:
print(first_vaccine_data['text'])
print(first_vaccine_data['text'][0])

0       Australia to Manufacture Covid 19 Vaccine and ...
1                            Australia is doing very good
2       Deaths due to COVID 19 in Affected Countries R...
3                          Subhashree Stay safe di amp da
4       This is what passes for leadership in our coun...
                              ...                        
4995                 What you don t know about schools 19
4996    This pledge by 9 global pharma companies NOT t...
4997                          Sure let them hurry up with
4998    Please watch this video from the Liberty Repor...
4999    Have you been collecting those aderalls that k...
Name: text, Length: 5000, dtype: object
Australia to Manufacture Covid 19 Vaccine and give it to the Citizens for free of cost AFP quotes Prime Minister


Train Data

In [13]:
#(0 = negative,  1 = neutral, 2 = positive)
test_data = pd.read_csv("/content/Twitter_Data.csv", nrows=5000)
test_data['category'] = test_data['category'] + 1
test_data.head() 


clean_text  category
0  when modi promised “minimum government maximum...         0
1  talk all the nonsense and continue all the dra...         1
2  what did just say vote for modi  welcome bjp t...         2
3  asking his supporters prefix chowkidar their n...         2
4  answer who among these the most powerful world...         2

# Pre-processing

In [14]:
#Tokenize Data
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

# Text DataSet

In [15]:
class GPReviewDataset(Dataset):
  def __init__(self, reviews, targets, tokenizer, max_len):
    self.reviews = reviews
    self.targets = targets
    self.tokenizer = tokenizer
    self.max_len = max_len
  def __len__(self):
    return len(self.reviews)
  def __getitem__(self, item):
    review = str(self.reviews[item])
    target = self.targets[item]
    encoding = self.tokenizer.encode_plus(
      review,
      add_special_tokens=True,
      max_length=self.max_len,
      return_token_type_ids=False,
      pad_to_max_length=True,
      return_attention_mask=True,
      return_tensors='pt',
    )
    return {
      'review_text': review,
      'input_ids': encoding['input_ids'].flatten(),
      'attention_mask': encoding['attention_mask'].flatten(),
      'targets': torch.tensor(target, dtype=torch.long)
    }

In [37]:
# 최대 토큰 길이
MAX_LEN = 120

In [38]:
df_train, df_test = train_test_split(
  test_data,
  test_size=0.1,
  random_state=RANDOM_SEED
)

df_val, df_test = train_test_split(
  df_test,
  test_size=0.5,
  random_state=RANDOM_SEED
)

print(df_train.shape)
print(df_val.shape)
print(df_test.shape)

(4500, 2)
(250, 2)
(250, 2)


In [39]:
def create_data_loader(df, tokenizer, max_len, batch_size):
  ds = GPReviewDataset(
    reviews=df['clean_text'].to_numpy(),
    targets=df['category'].to_numpy(),
    tokenizer=tokenizer,
    max_len=max_len
  )
  return DataLoader(
    ds,
    batch_size=batch_size,
    num_workers = 2
  )

In [40]:
print(df_train.columns)

Index(['clean_text', 'category'], dtype='object')


In [41]:
BATCH_SIZE = 8

train_data_loader = create_data_loader(df_train, tokenizer, MAX_LEN, BATCH_SIZE)
val_data_loader = create_data_loader(df_val, tokenizer, MAX_LEN, BATCH_SIZE)
test_data_loader = create_data_loader(df_test, tokenizer, MAX_LEN, BATCH_SIZE)

# Import Model

In [42]:
bert_model = BertModel.from_pretrained('bert-base-cased')

In [43]:
class SentimentClassifier(nn.Module):

  def __init__(self, n_classes):
    super(SentimentClassifier, self).__init__()
    self.bert = BertModel.from_pretrained('bert-base-cased')
    self.drop = nn.Dropout(p=0.3)
    self.out = nn.Linear(self.bert.config.hidden_size, n_classes)
  
  def forward(self, input_ids, attention_mask):
    _, pooled_output = self.bert(
      input_ids=input_ids,
      attention_mask=attention_mask
    )
    output = self.drop(pooled_output)
    return self.out(output)

In [44]:
class_names = ['negative', 'neutral', 'positive']

model = SentimentClassifier(len(class_names))
model = model.to(device)

In [45]:
data = next(iter(train_data_loader))

input_ids = data['input_ids'].to(device)
attention_mask = data['attention_mask'].to(device)
print(input_ids.shape) # batch size x seq length
print(attention_mask.shape) # batch size x seq length
print(input_ids[0])
print()

torch.Size([8, 120])
torch.Size([8, 120])
tensor([  101,  1107,  7168,  1209, 19004,  1216,  5471,  7042,  9468,  3702,
         1144,  1694,  1917,  1111,  2869,  1234,  1107,  7168,  1155,  1934,
         9319, 12006,  1132,  1111,  2869,  1234,   182,  5412,  1182,  1144,
         7894,  1105,  7042,  1444,  1359, 12006,  1111,  2869,  1234,  1443,
         1251,  7812, 11245,  2394,  5067,  5789,  1194,   173, 21238,   102,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0

In [46]:
F.softmax(model(input_ids, attention_mask), dim=1)

tensor([[0.3206, 0.2526, 0.4268],
        [0.2936, 0.1872, 0.5193],
        [0.2695, 0.2902, 0.4403],
        [0.2741, 0.2027, 0.5233],
        [0.3458, 0.2183, 0.4359],
        [0.3846, 0.1477, 0.4677],
        [0.2211, 0.2292, 0.5498],
        [0.2794, 0.1969, 0.5237]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

# Train

In [47]:
EPOCHS = 10
optimizer = AdamW(model.parameters(), lr=2e-5, correct_bias=False)
total_steps = len(train_data_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
  optimizer,
  num_warmup_steps=0,
  num_training_steps=total_steps
)
loss_fn = nn.CrossEntropyLoss().to(device)

In [48]:
def train_epoch(
  model,
  data_loader,
  loss_fn,
  optimizer,
  device,
  scheduler,
  n_examples
):
  model = model.train()
  losses = []
  correct_predictions = 0
  for d in data_loader:
    input_ids = d["input_ids"].to(device)
    attention_mask = d["attention_mask"].to(device)
    targets = d["targets"].to(device)
    outputs = model(
      input_ids=input_ids,
      attention_mask=attention_mask
    )
    _, preds = torch.max(outputs, dim=1)
    loss = loss_fn(outputs, targets)
    correct_predictions += torch.sum(preds == targets)
    losses.append(loss.item())
    loss.backward()
    nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
    optimizer.step()
    scheduler.step()
    optimizer.zero_grad()
  return correct_predictions.double() / n_examples, np.mean(losses)

In [49]:
def eval_model(model, data_loader, loss_fn, device, n_examples):
  model = model.eval()
  losses = []
  correct_predictions = 0
  with torch.no_grad():
    for d in data_loader:
      input_ids = d["input_ids"].to(device)
      attention_mask = d["attention_mask"].to(device)
      targets = d["targets"].to(device)
      outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask
      )
      _, preds = torch.max(outputs, dim=1)
      loss = loss_fn(outputs, targets)
      correct_predictions += torch.sum(preds == targets)
      losses.append(loss.item())
  return correct_predictions.double() / n_examples, np.mean(losses)

In [50]:
%%time
history = defaultdict(list)
best_accuracy = 0

for epoch in range(EPOCHS):
  print(f'Epoch {epoch + 1}/{EPOCHS}')
  print('-' * 10)
  train_acc, train_loss = train_epoch(
    model,
    train_data_loader,
    loss_fn,
    optimizer,
    device,
    scheduler,
    len(df_train)
  )
  print(f'Train loss {train_loss} accuracy {train_acc}')
  val_acc, val_loss = eval_model(
    model,
    val_data_loader,
    loss_fn,
    device,
    len(df_val)
  )
  print(f'Val   loss {val_loss} accuracy {val_acc}')
  print()
  history['train_acc'].append(train_acc)
  history['train_loss'].append(train_loss)
  history['val_acc'].append(val_acc)
  history['val_loss'].append(val_loss)
  if val_acc > best_accuracy:
    torch.save(model.state_dict(), 'best_model_state.bin')
    best_accuracy = val_acc

Epoch 1/10
----------
Train loss 0.9825234341684921 accuracy 0.5175555555555555
Val   loss 0.9427569853141904 accuracy 0.648

Epoch 2/10
----------
Train loss 0.6544475723488081 accuracy 0.7611111111111112
Val   loss 0.5846451097168028 accuracy 0.768

Epoch 3/10
----------
Train loss 0.4779715116994313 accuracy 0.8546666666666667
Val   loss 0.5931397125241347 accuracy 0.8240000000000001

Epoch 4/10
----------
Train loss 0.3607856690284811 accuracy 0.912
Val   loss 0.7256907430564752 accuracy 0.856

Epoch 5/10
----------
Train loss 0.2861247590493219 accuracy 0.9375555555555556
Val   loss 0.8264174109644955 accuracy 0.844

Epoch 6/10
----------
Train loss 0.21781366949381561 accuracy 0.9544444444444445
Val   loss 0.7921610357443569 accuracy 0.84

Epoch 7/10
----------
Train loss 0.17782489612961574 accuracy 0.9660000000000001
Val   loss 0.6717753960838309 accuracy 0.868

Epoch 8/10
----------
Train loss 0.14030731066860438 accuracy 0.9733333333333334
Val   loss 0.7761117212066893 accura

# Test Raw Text

In [51]:
example = first_vaccine_data["text"][0:10]
for text in example:
  print("text: " +text)

text: Australia to Manufacture Covid 19 Vaccine and give it to the Citizens for free of cost AFP quotes Prime Minister
text: Australia is doing very good
text: Deaths due to COVID 19 in Affected Countries Read More piryani
text: Subhashree Stay safe di amp da
text: This is what passes for leadership in our country a voucher for something that w
text: The Multi system Inflammatory Syndrome Children MIS C w atypical Kawasaki disease The
text: 88
text: Well let s qualify that would anyone of any party get a vaccine rushed out and minimally tested coming from Russia
text: Most countries without the ability to make locally will be forced to rely on others like the US China
text: zooms up charts in 1st week hear episode


In [52]:
encoded_example = []

for data in example:
  encoded_tweet = tokenizer.encode_plus(
  data,
  max_length=MAX_LEN,
  add_special_tokens=True,
  return_token_type_ids=False,
  pad_to_max_length=True,
  return_attention_mask=True,
  return_tensors='pt',
)
  encoded_example.append(encoded_tweet)

In [53]:
for encoded_data in encoded_example:
  input_ids = encoded_data['input_ids'].to(device)
  attention_mask = encoded_data['attention_mask'].to(device)
  output = model(input_ids, attention_mask)
  _, prediction = torch.max(output, dim=1)

  print(prediction)


tensor([2], device='cuda:0')
tensor([2], device='cuda:0')
tensor([0], device='cuda:0')
tensor([2], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([0], device='cuda:0')
tensor([2], device='cuda:0')


Analsys Data

In [56]:
first_vaccine_data = pd.read_csv("/content/covidvaccine.csv", nrows = 100000)
second_vaccine_data = pd.read_csv("/content/vaccination_all_tweets.csv", nrows = 100000)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (5,6,7,12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [93]:
data_column = ['user_name', 'user_description','user_location','user_followers','text']
first_vaccine_data = first_vaccine_data[data_column]
second_vaccine_data = second_vaccine_data[data_column]
analysis_data = pd.concat([first_vaccine_data,second_vaccine_data], ignore_index=True)
  
analysis_data['text'].dropna()
for index, data in analysis_data.iterrows():
  if type(data["text"]) != str:
    analysis_data.drop(index)

In [96]:
def con_analysis(x):
  return ''.join(re.sub("(#[A-Za-z0-9]+)|(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",str(x)).split())

analysis_data['text'] = analysis_data['text'].apply(con_analysis)
analysis_data.drop_duplicates()
analysis_data.head()

user_name  ...                                               text
0                 MyNewsNE  ...  AustraliatoManufactureCovid19Vaccineandgiveitt...
1            Shubham Gupta  ...                           Australiaisdoingverygood
2  Journal of Infectiology  ...  DeathsduetoCOVID19inAffectedCountriesReadMorep...
3                     Zane  ...                          SubhashreeStaysafediampda
4       Ann-Maree O’Connor  ...  Thisiswhatpassesforleadershipinourcountryavouc...

[5 rows x 5 columns]

In [97]:
print(analysis_data.shape)

(200000, 5)


In [98]:
sentiment_label = []
encoded_text = []
for text in analysis_data['text']:
  encoded_tweet = tokenizer.encode_plus(
  text,
  max_length=MAX_LEN,
  add_special_tokens=True,
  return_token_type_ids=False,
  pad_to_max_length=True,
  return_attention_mask=True,
  return_tensors='pt',
)
  encoded_text.append(encoded_tweet)

In [ ]:
for encoded_data in encoded_text:
  input_ids = encoded_data['input_ids'].to(device)
  attention_mask = encoded_data['attention_mask'].to(device)
  output = model(input_ids, attention_mask)
  _, prediction = torch.max(output, dim=1)
  sentiment_label.append(prediction)